### ISSUE TITLE
No button

### ISSUE THREAD

**Issue by far-thole** [ele-ala-ele/pixiv_ugoira_gif#1]
As far as I am aware, it no longer works on Firefox (using Greasemonkey). I viewed the [image that accompanied the introduction of ugoira](http://www.pixiv.net/member_illust.php?illust_id=44298524&mode=medium), and the button doesn't appear near the bookmark button or anywhere else at all.

**Comment by ele-ala-ele** [comment]
Hello and thanks for your feedback. I just tested it in Firefox 47 and it works as intended. The "Create!" button is supposed to be right below the ugoira animation and it appears right there. Also, clicking the button performs the intended action without any problems. I would like to know more details about your system and or browser version in order to know what can I do to fix the problem you're having. Thanks in advance.

**Comment by far-thole** [comment]
I stuffed up. Never mind, I mistook this script for another one (ugoira2gif). This one works perfectly fine. Apologies for having wasted your time, and thanks for creating this script. Please delete this.

**Comment by ele-ala-ele** [comment]
No problem. Thanks to you for using it.
